---
title: "Data Transformations"
author: "Grace Kosieradzki"
date: "4/26/2024"
output:
  pdf_document: default
  html_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = TRUE)
library(tidyverse)
library(ggplot2)
library(readr)
library(dplyr)

```



## Apple Transparency
```{r}
##READ CSV's
us_national_security_requests <- read_csv("trans-data/Apple_Transparency_Report/us_national_security_requests.csv") 
push_token_requests <- read_csv("trans-data/Apple_Transparency_Report/push_token_requests.csv")
financial_identifier_requests <- read_csv("trans-data/Apple_Transparency_Report/financial_identifier_requests.csv")
emergency_requests <- read_csv("trans-data/Apple_Transparency_Report/emergency_requests.csv")
digital_content_provider_requests <- read_csv("trans-data/Apple_Transparency_Report/digital_content_provider_requests.csv")
device_requests <- read_csv("trans-data/Apple_Transparency_Report/device_requests.csv")
account_restriction_deletion_requests <- read_csv("trans-data/Apple_Transparency_Report/account_restriction_deletion_requests.csv")
account_requests <- read_csv("trans-data/Apple_Transparency_Report/account_requests.csv")
account_preservation_requests <- read_csv("trans-data/Apple_Transparency_Report/account_preservation_requests.csv")


## DATA TRANSFORMATIONS
# All data after transformations are US only

#Gathers identifying details of accounts that receive certain push notifs
us_push_token_requests <- push_token_requests |>            # Only one row of data in the US during 2022 H2
  filter(`Country/Region` == "United States of America") |> # Before this push token requests were in account/device requests
  rename(push_requests = `Push Token Requests Received`,
         push_provided = `Requests where Data Provided`,
         push_percent = `Percentage of Requests where Data Provided`) |> 
  select(!c(`Country/Region`, `Push Tokens Specified in Requests`)) |> 
  mutate(push_percent = as.double(str_sub(push_percent, end=2))/100)
  
#Seeking financial identifiers (credit/debit card info) usually during suspected fraud cases
us_financial_identifier_requests <- financial_identifier_requests |>
  filter(`Country/Region` == "United States of America") |> 
  rename(financial_requests = `Financial Identifier Requests Received`,
         financial_provided = `Requests where Data Provided`,
         financial_percent = `Percentage of Requests where Data Provided`)  |> 
  select(!c(`Financial Identifiers Specified in Requests`, `Country/Region`)) |> 
  mutate(financial_percent = ifelse(nchar(financial_percent) == 4,                       #change percent from str to double
                                 yes = as.double(str_sub(financial_percent, end=3))/100,
                                 no = as.double(str_sub(financial_percent, end=2))/100)) 

#Seeking customer connection to apple services when there is imminent danger to a person (i.e accessing find my friend data for a missing person case)
us_emergency_requests <- emergency_requests |> 
  filter(`Country/Region` == "United States of America") |> 
  rename(emergency_requests = `Emergency Requests Received`,
         emergency_provided = `Requests where Data Provided`,
         emergency_percent = `Percentage of Requests where Data Provided`) |>
  select(!c(`Requests where No Data Provided`, `Country/Region`, `Requests Rejected/Challenged and No Data Provided`)) |> 
  mutate(emergency_provided = ifelse(emergency_provided == '-', 0, emergency_provided),
         emergency_provided = as.double(emergency_provided),
         emergency_percent = ifelse(emergency_percent == '-', 0, emergency_percent),
         emergency_percent = ifelse(nchar(emergency_percent) == 4,
                                 yes = as.double(str_sub(emergency_percent, end=3))/100,
                                 no = as.double(str_sub(emergency_percent, end=2))/100))

#Seeking info of content providers who are suspected of violating local law 
us_digital_content_provider_requests <- digital_content_provider_requests |> 
    filter(`Country/Region` == "United States of America") |> 
    rename(content_requests =  `Digital Content Provider Requests Received`,
           content_provided = `Requests where Data Provided`,
           content_percent = `Percentage of Requests where Data Provided`) |> 
    select(!c(`Country/Region`, `Requests Objected in Part or Rejected in Full`)) |> 
  mutate(content_percent = ifelse(nchar(content_percent) == 4,                         
                                  yes = as.double(str_sub(content_percent, end=3))/100, 
                                  no = as.double(str_sub(content_percent, end=2))/100))

#Seeking info of people with specific device serial number
us_device_requests <- device_requests |> 
    filter(`Country/Region` == "United States of America") |> 
    rename(device_requests = `Device Requests Received`,
           device_provided = `Requests where Data Provided`,
           device_percent = `Percentage of Requests where Data Provided`) |> 
    select(!c(`Country/Region`, `Devices Specified in Requests`)) |> 
  mutate(device_percent = ifelse(nchar(device_percent) == 4,
                                 yes = as.double(str_sub(device_percent, end=3))/100,
                                 no = as.double(str_sub(device_percent, end=2))/100)) 
          

#Requests to restrict or delete a user's account
us_account_restriction_deletion_requests <- account_restriction_deletion_requests |> 
    filter(`Country/Region` == "United States of America") |> 
    rename(deletion_restriction_requests = `Account Restriction/ Account Deletion Requests Received`,
           restriction_provided = `Requests where Account Restricted`,
           deletion_provided = `Requests where Account Deleted`) |>           
    mutate(deletion_restriction_percent = 1 - (`Requests Rejected/Challenged where No Action Taken` / deletion_restriction_requests)) |>#calculates % manually
    mutate(restriction_provided = ifelse(restriction_provided == '-', yes = 0, no = restriction_provided),
           restriction_provided = as.double(restriction_provided),) |> 
    select(!c(`Country/Region`, `Accounts Specified in the Requests`, `Requests Rejected/Challenged where No Action Taken`)) 
    
 
#Requests for account identifiers like Apple ID but also sometimes included content requests such as photos and contacts
us_account_requests <- account_requests |> 
    filter(`Country/Region` == "United States of America") |> 
    rename(account_requests =`Account Requests Received`,
           account_noncontent_provided = `Requests where Only Non-Content Data Provided`,
           account_content_provided = `Requests where Content Provided`,
           account_percent =`Percentage of Requests where Data Provided`) |> 
    select(!c(`Country/Region`, `Accounts Specified in Requests`, `Requests Challenged in Part or Rejected in Full`)) |> 
    mutate(account_percent = ifelse(nchar(account_percent) == 4,
                                 yes = as.double(str_sub(account_percent, end=3))/100,
                                 no = as.double(str_sub(account_percent, end=2))/100))

#Requests for apple to preserve a one time copy of customer's account data while legal requests are being obtained
#Not being used in the final analysis
us_account_preservation_requests <- account_preservation_requests |> 
    filter(`Country/Region` == "United States of America") |> 
    rename(`TR Period` = `TR Date`,
           preservation_requests = `Account Preservation Requests Received`,
           preservation_account_count = `Accounts Specified in Requests`,
           preservation_provided = `Accounts where Data Preserved`) |> 
    mutate(preservation_percent = preservation_provided / preservation_account_count) |>  
    select(!c(`Country/Region`))


apple_us_transp <- full_join(us_financial_identifier_requests, us_emergency_requests, by=c("TR Period", "TR Start Date", "TR End Date")) |> 
  full_join(us_digital_content_provider_requests, by=c("TR Period", "TR Start Date", "TR End Date")) |> 
  full_join(us_device_requests, by=c("TR Period", "TR Start Date", "TR End Date")) |> 
  full_join(us_account_restriction_deletion_requests, by=c("TR Period", "TR Start Date", "TR End Date")) |> 
  full_join(us_account_requests, by=c("TR Period", "TR Start Date", "TR End Date"))

apple_us_transp[is.na(apple_us_transp)] <- 0

apple_us_transp <- apple_us_transp |> 
  group_by(`TR Period`) |> 
  mutate(total_requests_apple = sum(across(ends_with("requests"))),
         total_provided_apple = sum(across(ends_with("provided"))),
         total_percent_apple = total_provided_apple / total_requests_apple,
         period_end = as.Date(`TR End Date`, "%m/%d/%y")) |> 
  ungroup() |> 
  select(c(total_requests_apple, total_provided_apple, total_percent_apple, period_end))
```

## Google Transparency
```{r, eval=FALSE}
google_global_user_data_requests <- read_csv("trans-data/google-user-data-requests/google-user-data-requests/google-global-user-data-requests.csv")


google_us_transp <- google_global_user_data_requests |> 
  filter(`Country/Region`== "United States",
         `Legal Process` != "Preservation Requests") |> 
  mutate(`Percentage disclosed` = `Percentage disclosed` / 100,
    user_provided = `User Data Requests` * `Percentage disclosed`) |>
  group_by(`Period Ending`) |> 
  mutate(total_requests_google = sum(`User Data Requests`),
         user_provided = sum(`user_provided`),
         total_percent_google = user_provided / total_requests_google,
         total_accounts_google = sum(Accounts))  |> 
  summarise(across(starts_with("total"), max)) |> 
  ungroup() |> 
  mutate(period_end = as.Date(`Period Ending`)) |> 
  select(!`Period Ending`)

google_us_transp[is.na(google_us_transp)] <- 0

```

## Meta Cleaning
```{r}
PRPL_Facebook_Government_Report_2023_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2023_H1.csv")

PRPL_Facebook_Government_Report_2022_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2022_H1.csv")
PRPL_Facebook_Government_Report_2022_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2022_H2.csv")

PRPL_Facebook_Government_Report_2021_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2021_H1.csv")
PRPL_Facebook_Government_Report_2021_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2021_H2.csv")

PRPL_Facebook_Government_Report_2020_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2020_H1.csv")
PRPL_Facebook_Government_Report_2020_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2020_H2.csv")

PRPL_Facebook_Government_Report_2019_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2019_H1.csv")
PRPL_Facebook_Government_Report_2019_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2019_H2.csv")

PRPL_Facebook_Government_Report_2018_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2018_H1.csv")
PRPL_Facebook_Government_Report_2018_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2018_H2.csv")

PRPL_Facebook_Government_Report_2017_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2017_H1.csv")
PRPL_Facebook_Government_Report_2017_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2017_H2.csv")

PRPL_Facebook_Government_Report_2016_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2016_H1.csv")
PRPL_Facebook_Government_Report_2016_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2016_H2.csv")

PRPL_Facebook_Government_Report_2015_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2015_H1.csv")
PRPL_Facebook_Government_Report_2015_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2015_H2.csv")

PRPL_Facebook_Government_Report_2014_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2014_H1.csv")
PRPL_Facebook_Government_Report_2014_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2014_H2.csv")

PRPL_Facebook_Government_Report_2013_H1 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2013_H1.csv")
PRPL_Facebook_Government_Report_2013_H2 <- read_csv("trans-data/meta-government-requests/PRPL-Facebook-Government-Report-2013_H2.csv")


meta_2023_H1 <- PRPL_Facebook_Government_Report_2023_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2023"))

meta_2022_H1 <- PRPL_Facebook_Government_Report_2022_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total")))|> 
  mutate(period_end = mdy("6/30/2022"))
meta_2022_H2 <- PRPL_Facebook_Government_Report_2022_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2022"))

meta_2021_H1 <- PRPL_Facebook_Government_Report_2021_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2021"))
meta_2021_H2 <- PRPL_Facebook_Government_Report_2021_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2021"))

meta_2020_H1 <- PRPL_Facebook_Government_Report_2020_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total")))|> 
  mutate(period_end = mdy("6/30/2020"))
meta_2020_H2 <- PRPL_Facebook_Government_Report_2020_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2020"))

meta_2019_H1 <- PRPL_Facebook_Government_Report_2019_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2019"))
meta_2019_H2 <- PRPL_Facebook_Government_Report_2019_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2019"))

meta_2018_H1 <- PRPL_Facebook_Government_Report_2018_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2018"))
meta_2018_H2 <- PRPL_Facebook_Government_Report_2018_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2018"))

meta_2017_H1 <- PRPL_Facebook_Government_Report_2017_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2017"))
meta_2017_H2 <- PRPL_Facebook_Government_Report_2017_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2017"))

meta_2016_H1 <- PRPL_Facebook_Government_Report_2016_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2016"))
meta_2016_H2 <- PRPL_Facebook_Government_Report_2016_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2016"))

meta_2015_H1 <- PRPL_Facebook_Government_Report_2015_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2015"))
meta_2015_H2 <- PRPL_Facebook_Government_Report_2015_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2015"))

meta_2014_H1 <- PRPL_Facebook_Government_Report_2014_H1 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2014"))
meta_2014_H2 <- PRPL_Facebook_Government_Report_2014_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2014"))

meta_2013_H1 <- PRPL_Facebook_Government_Report_2013_H1 |> 
  filter(Country == "United States") |> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("6/30/2013"))
meta_2013_H2 <- PRPL_Facebook_Government_Report_2013_H2 |> 
  filter(Country == "United States")|> 
  select(c(starts_with("Total"))) |> 
  mutate(period_end = mdy("12/31/2013"))

meta_us_transp <- list(meta_2013_H1,meta_2013_H2, meta_2014_H1, meta_2014_H2, meta_2015_H1, meta_2015_H2, meta_2016_H1, meta_2016_H2, meta_2017_H1, meta_2017_H2, meta_2018_H1, meta_2018_H2, meta_2019_H1, meta_2019_H2, meta_2020_H1, meta_2020_H2, meta_2021_H1, meta_2021_H2, meta_2022_H1, meta_2022_H2, meta_2023_H1)


meta_us_transp <-do.call("rbind", meta_us_transp) |> 
  as_tibble() |> 
  rename(total_percent_meta = "Total Requests Percentage",
         total_requests_meta = "Total Requests",
         total_accounts_meta =  "Total Requests Accounts") |> 
  mutate(total_percent_meta = ifelse(nchar(total_percent_meta) == 4,
                                 yes = as.double(str_sub(total_percent_meta, end=3))/100,
                                 no = as.double(str_sub(total_percent_meta, end=2))/100)) 

```


## Combining Datasets
```{r}
full_us_transp <-  merge(google_us_transp, apple_us_transp)
full_us_transp <- merge(full_us_transp, meta_us_transp)

full_us_transp |> 
  ggplot(aes(x=period_end)) +
  geom_line(aes(y=total_percent_google,color="Google")) +
  geom_line(aes(y=total_percent_apple, color="Apple")) +
  geom_line(aes(y=total_percent_meta, color="Meta")) +
  labs(title = "Government Compliance Based on Company",
       x = "Year",
       y = "Percent Compliance",
       colour = "Company")
```